### ISSUE TITLE
Listar leituras adicionais e cor litúrgica

### ISSUE THREAD

**Issue by SrMouraSilva** [viniciusdacal/liturgia-diaria#4]
Seria interessante que no JSON retornado também contivesse as leituras opcionais expostas na tela

**Comment by viniciusdacal** [comment]
Sim, seria interessante.
Outra coisa que também poderia ter, é a cor do dia.
Infelizmente, ali no site da cnbb eu não encontrei um lugar que tenha o santo do dia. Se tivesse, ai ficaria completo!

**Comment by SrMouraSilva** [comment]
Nem tinha visto que tinha a cor!

Agora, abaixo do título as vezes tem uns nomes. Olha:
http://liturgiadiaria.cnbb.org.br/app/user/user/UserView.php?mes=6&ano=2015

**Comment by SrMouraSilva** [comment]
Na verdade, as leituras adicionais já eram listadas. O que não ocorria era separação entre elas.
Commitarei em breve a correção
