### ISSUE TITLE
Arquivos da Liturgia Diária em formato JSON

### ISSUE THREAD

**Issue by celsosz** [viniciusdacal/liturgia-diaria#6]
Oi @viniciusdacal, tudo bem?

Você tem os arquivos da Liturgia Diária em formato JSON? Se sim, como você poderia me disponibilizar?

Abraços,
Celso.

**Comment by viniciusdacal** [comment]
@celsosz não existem arquivos JSON da liturgia, ele projeto é apenas um crowler. Utilizando ele, você conseguiria capturar o conteúdo e criar arquivos JSON.

**Comment by ismaaelvale** [comment]
Existe uma api publica para leitura da liturgia diária? preciso implementar na minha paróquia.
