### ISSUE TITLE
duvida

### ISSUE THREAD

**Issue by caldeirainformatica** [viniciusdacal/liturgia-diaria#7]
Boa noite, essa solução foi descontinuada?

**Comment by viniciusdacal** [comment]
Nunca mais fizemos atualizações. Se o site da liturgia diária foi atualizado, o script provavelmente não está mais funcionando. Contribuições são bem vindas

**Comment by caldeirainformatica** [comment]
Realmente, não está retornando nada.
Estou tentando aqui, mas com dificuldades em pegar o html e transformar em json ou qualquer outro formato que eu possa manusear.

Até o momento peguei as informações assim.

 $c = curl_init();
    curl_setopt($c, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($c, CURLOPT_URL, "https://liturgiadiaria.cnbb.org.br/app/user/user/UserView.php?ano=2019&mes=12&dia=10");
    $contents = curl_exec($c);
    curl_close($c);
    
    return $contents;

Alguma luz para me ajudar?

**Comment by caldeirainformatica** [comment]
Bom dia irmão.
Fiz aqui usando Laravel e PHP. Mas acredito que as funções funcionam em outras plataformas...
A dificuldade está em separar, por exemplo no salmo, a parte da resposta do restante da leitura.

 public function getLiturgia($leitura)
    {
        $doc = new DOMDocument();
        libxml_use_internal_errors(true);
        $doc->loadHTMLFile("https://liturgiadiaria.cnbb.org.br/app/user/user/UserView.php?ano=2019&mes=12&dia=16");
        $h1 = $doc->getElementById("corpo_leituras");
        $newdoc = new DOMDocument();
        $cloned = $h1->cloneNode(TRUE);
        $newdoc->appendChild($newdoc->importNode($cloned, TRUE));
        $doc = new DOMDocument();
        $doc->loadHTML($newdoc->saveHTML());
        $list = $doc->getElementsByTagName("script");
        while ($list->length > 0) {
            $p = $list->item(0);
            $p->parentNode->removeChild($p);
        }
        libxml_clear_errors();
        $h1 = $doc->getElementById("corpo_leituras")->childNodes;
        $retorno = [];
        //print_r($h1->item(1)->C14N());
        foreach ($h1 as $node) {
            array_push($retorno, $node);
        }
        $retorno2 = [];
        foreach ($retorno as $key => $valor) {
            if($valor instanceof  \DOMElement){
//                print_r($valor);
                array_push($retorno2, [
                    'titulo' => trim(preg_replace('/\s+/', ' ', $valor->childNodes[1]->textContent)),
                    'leitura' => trim(preg_replace('/\s+/', ' ', $valor->childNodes[5]->textContent))
                ]);
            }

            /*$valor = [
                'titulo' => $valor,
                'html' => $valor[5]
            ];
                array_push($retorno2, $valor);*/


        }
        /* 
        variavel leitura recebe 0, 1, 2, 3
        Sendo que 0 = Primeira leitura, 1 = Salmo, 2 = segunda leitura, 3 = evangelho 
        */
        return response()->json($retorno2[$leitura]); 
    }

**Comment by caldeirainformatica** [comment]
Bom dia irmão.
Fiz aqui usando Laravel e PHP. Mas acredito que as funções funcionam em outras plataformas...
A dificuldade está em separar, por exemplo no salmo, a parte da resposta do restante da leitura.
`
public function getLiturgia($leitura)
{
$doc = new DOMDocument();
libxml_use_internal_errors(true);
$doc->loadHTMLFile("https://liturgiadiaria.cnbb.org.br/app/user/user/UserView.php?ano=2019&mes=12&dia=16");
$h1 = $doc->getElementById("corpo_leituras");
$newdoc = new DOMDocument();
$cloned = $h1->cloneNode(TRUE);
$newdoc->appendChild($newdoc->importNode($cloned, TRUE));
$doc = new DOMDocument();
$doc->loadHTML($newdoc->saveHTML());
$list = $doc->getElementsByTagName("script");
while ($list->length > 0) {
$p = $list->item(0);
$p->parentNode->removeChild($p);
}
libxml_clear_errors();
$h1 = $doc->getElementById("corpo_leituras")->childNodes;
$retorno = [];
//print_r($h1->item(1)->C14N());
foreach ($h1 as $node) {
array_push($retorno, $node);
}
$retorno2 = [];
foreach ($retorno as $key => $valor) {
if($valor instanceof \DOMElement){
// print_r($valor);
array_push($retorno2, [
'titulo' => trim(preg_replace('/\s+/', ' ', $valor->childNodes[1]->textContent)),
'leitura' => trim(preg_replace('/\s+/', ' ', $valor->childNodes[5]->textContent))
]);
}

        /*$valor = [
            'titulo' => $valor,
            'html' => $valor[5]
        ];
            array_push($retorno2, $valor);*/


    }
    /* 
    variavel leitura recebe 0, 1, 2, 3
    Sendo que 0 = Primeira leitura, 1 = Salmo, 2 = segunda leitura, 3 = evangelho 
    */
    return response()->json($retorno2[$leitura]); 
}
`

**Comment by caldeirainformatica** [comment]
Bom dia irmão.
Fiz aqui usando Laravel e PHP. Mas acredito que as funções funcionam em outras plataformas...
A dificuldade está em separar, por exemplo no salmo, a parte da resposta do restante da leitura.

`public function getLiturgia($leitura)
{
$doc = new DOMDocument();
libxml_use_internal_errors(true);
$doc->loadHTMLFile("https://liturgiadiaria.cnbb.org.br/app/user/user/UserView.php?ano=2019&mes=12&dia=16");
$h1 = $doc->getElementById("corpo_leituras");
$newdoc = new DOMDocument();
$cloned = $h1->cloneNode(TRUE);
$newdoc->appendChild($newdoc->importNode($cloned, TRUE));
$doc = new DOMDocument();
$doc->loadHTML($newdoc->saveHTML());
$list = $doc->getElementsByTagName("script");
while ($list->length > 0) {
$p = $list->item(0);
$p->parentNode->removeChild($p);
}
libxml_clear_errors();
$h1 = $doc->getElementById("corpo_leituras")->childNodes;
$retorno = [];
//print_r($h1->item(1)->C14N());
foreach ($h1 as $node) {
array_push($retorno, $node);
}
$retorno2 = [];
foreach ($retorno as $key => $valor) {
if($valor instanceof \DOMElement){
// print_r($valor);
array_push($retorno2, [
'titulo' => trim(preg_replace('/\s+/', ' ', $valor->childNodes[1]->textContent)),
'leitura' => trim(preg_replace('/\s+/', ' ', $valor->childNodes[5]->textContent))
]);
}

    /*$valor = [
        'titulo' => $valor,
        'html' => $valor[5]
    ];
        array_push($retorno2, $valor);*/


}
/* 
variavel leitura recebe 0, 1, 2, 3
Sendo que 0 = Primeira leitura, 1 = Salmo, 2 = segunda leitura, 3 = evangelho 
*/
return response()->json($retorno2[$leitura]); 
}`

**Comment by ismaaelvale** [comment]
> Bom dia irmão.
> Fiz aqui usando Laravel e PHP. Mas acredito que as funções funcionam em outras plataformas...
> A dificuldade está em separar, por exemplo no salmo, a parte da resposta do restante da leitura.
> 
> `public function getLiturgia($leitura)
> {
> $doc = new DOMDocument();
> libxml_use_internal_errors(true);
> $doc->loadHTMLFile("https://liturgiadiaria.cnbb.org.br/app/user/user/UserView.php?ano=2019&mes=12&dia=16");
> $h1 = $doc->getElementById("corpo_leituras");
> $newdoc = new DOMDocument();
> $cloned = $h1->cloneNode(TRUE);
> $newdoc->appendChild($newdoc->importNode($cloned, TRUE));
> $doc = new DOMDocument();
> $doc->loadHTML($newdoc->saveHTML());
> $list = $doc->getElementsByTagName("script");
> while ($list->length > 0) {
> $p = $list->item(0);
> $p->parentNode->removeChild($p);
> }
> libxml_clear_errors();
> $h1 = $doc->getElementById("corpo_leituras")->childNodes;
> $retorno = [];
> //print_r($h1->item(1)->C14N());
> foreach ($h1 as $node) {
> array_push($retorno, $node);
> }
> $retorno2 = [];
> foreach ($retorno as $key => $valor) {
> if($valor instanceof \DOMElement){
> // print_r($valor);
> array_push($retorno2, [
> 'titulo' => trim(preg_replace('/\s+/', ' ', $valor->childNodes[1]->textContent)),
> 'leitura' => trim(preg_replace('/\s+/', ' ', $valor->childNodes[5]->textContent))
> ]);
> }
> 
> ```
> /*$valor = [
>     'titulo' => $valor,
>     'html' => $valor[5]
> ];
>     array_push($retorno2, $valor);*/
> ```
> 
> }
> /*
> variavel leitura recebe 0, 1, 2, 3
> Sendo que 0 = Primeira leitura, 1 = Salmo, 2 = segunda leitura, 3 = evangelho
> */
> return response()->json($retorno2[$leitura]);
> }`

Boa noite.

Você pode me ajudar a implementar essa solução no aplicativo de minha paroquia? Sou iniciante em programação android studio, e estou desenvolvendo uma aplicação para minha paróquia.

**Comment by SrMouraSilva** [comment]
@ismaaelvale, bom dia.

Esta solução é feita em PHP. Não é possível utilizar esse código diretamente no aplicativo. O ideal seria que o aplicativo consumisse uma API.

Esse código foi justamente pensado para fornecer uma API. Ele faz um _scrapping_ da página e fornece os dados. Entretanto, está há muito tempo sem manutenção, de forma que se houve alguma atualização no html da página, essa solução não funciona mais. 

Observe que o código foi disponibilizado, mas não um serviço. Ou seja, se você quisesse utilizar, seria necessário subir um servidor para tal, o que incluiria maquinário ou então a contratação de algum serviço na internet.

Recomendo que você faça uma coisa mais simples. Coloque uma `WebView` para abrir a página liturgiadiaria.cnbb.org.br.

**Comment by SrMouraSilva** [comment]
@ismaaelvale, um adendo: Já existem alguns aplicativos de liturgia diária. Você poderia tentar conversar com as equipes, or exemplo a da Liturgia Diária https://play.google.com/store/apps/details?id=com.cancaonova.liturgia&hl=pt_BR&gl=US. No final do link tem o email de contato deles.

Recomendo que você pergunte qual a [`Intent`](https://developer.android.com/guide/components/intents-filters?hl=pt-br) que deve ser chamada para abrir no aplicativo deles a página da liturgia do dia

**Comment by ismaaelvale** [comment]
Valeu pela ajuda.

Em dom, 11 de abr de 2021 10:22, Paulo Mateus ***@***.***>
escreveu:
